// ── 第九十九锤:开发者命名词根词典 ──
// 程序员的命名翻来覆去就两三百个词(scanner/parser/router……),名字本身就是文件最大的信息量。
// 这里把名字拆成单词逐个查表,拼回一句中文:GitFileStatus → git文件状态,scanner → 扫描器。
// 纯查表、零成本、离线;认不出的词不硬翻 —— 查不出任何词就如实退回原来的兜底链。

/** 词根表:小写词 → 中文(缩写词映射回原样,留在合成词里当身份) */
export const WORD_BOOK: Record<string, string> = {
  // ── 角色/职责 ──
  scanner: '扫描器',
  scan: '扫描',
  parser: '解析器',
  parse: '解析',
  analyzer: '分析器',
  analyse: '分析',
  analyze: '分析',
  summarizer: '摘要器',
  summary: '摘要',
  digest: '摘要',
  formatter: '格式化器',
  format: '格式化',
  locator: '定位器',
  locate: '定位',
  validator: '校验器',
  validate: '校验',
  verifier: '校验器',
  verify: '校验',
  checker: '检查器',
  check: '检查',
  handler: '处理器',
  controller: '控制器',
  service: '服务',
  manager: '管理器',
  builder: '构建器',
  build: '构建',
  renderer: '渲染器',
  render: '渲染',
  compiler: '编译器',
  compile: '编译',
  tokenizer: '分词器',
  lexer: '词法分析',
  detector: '检测器',
  detect: '检测',
  extractor: '提取器',
  extract: '提取',
  transformer: '转换器',
  transform: '转换',
  generator: '生成器',
  generate: '生成',
  mapper: '映射器',
  map: '映射',
  adapter: '适配器',
  bridge: '桥接',
  proxy: '代理',
  wrapper: '包装器',
  helper: '辅助',
  util: '工具',
  utils: '工具',
  tool: '工具',
  watcher: '监视器',
  watch: '监视',
  observer: '观察者',
  listener: '监听器',
  dispatcher: '分发器',
  resolver: '求解器',
  factory: '工厂',
  provider: '提供者',
  registry: '注册表',
  visitor: '访问器',
  walker: '遍历器',
  runner: '运行器',
  loader: '加载器',
  saver: '保存器',
  cleaner: '清理器',
  counter: '计数器',
  estimator: '估算器',
  calculator: '计算器',
  translator: '翻译器',
  explorer: '浏览器',
  inspector: '检查器',
  predictor: '预测器',
  recommender: '推荐器',
  // ── 结构/位置 ──
  core: '核心',
  common: '公共',
  shared: '共享',
  module: '模块',
  modules: '模块',
  package: '包',
  plugin: '插件',
  plugins: '插件',
  extension: '扩展',
  node: '节点',
  edge: '边',
  graph: '图',
  tree: '树',
  list: '列表',
  table: '表格',
  grid: '网格',
  pool: '池',
  queue: '队列',
  stack: '栈',
  buffer: '缓冲',
  stream: '流',
  pipe: '管道',
  chain: '链',
  entry: '入口',
  exit: '出口',
  gateway: '网关',
  bridgehead: '桥头',
  context: '上下文',
  state: '状态',
  status: '状态',
  data: '数据',
  store: '存储',
  storage: '存储',
  cache: '缓存',
  session: '会话',
  registrykeys: '注册表',
  config: '配置',
  configuration: '配置',
  setting: '设置',
  settings: '设置',
  preference: '偏好',
  options: '选项',
  env: '环境',
  // ── 界面 ──
  view: '视图',
  page: '页面',
  screen: '屏幕',
  layout: '布局',
  widget: '部件',
  component: '组件',
  dialog: '对话框',
  panel: '面板',
  card: '卡片',
  form: '表单',
  input: '输入',
  button: '按钮',
  menu: '菜单',
  nav: '导航',
  navigation: '导航',
  header: '页头',
  footer: '页脚',
  sidebar: '侧栏',
  modal: '弹窗',
  toast: '轻提示',
  badge: '徽章',
  icon: '图标',
  theme: '主题',
  style: '样式',
  styles: '样式',
  css: '样式',
  color: '颜色',
  font: '字体',
  asset: '资源',
  assets: '资源',
  image: '图片',
  audio: '音频',
  video: '视频',
  media: '媒体',
  canvas: '画布',
  chart: '图表',
  window: '窗口',
  tab: '标签页',
  tabs: '标签页',
  breadcrumb: '面包屑',
  preview: '预览',
  editor: '编辑器',
  animation: '动画',
  motion: '动效',
  gesture: '手势',
  drag: '拖拽',
  scroll: '滚动',
  zoom: '缩放',
  keyboard: '键盘',
  mouse: '鼠标',
  cursor: '光标',
  caret: '光标',
  spinner: '加载圈',
  progress: '进度',
  // ── 数据/网络 ──
  file: '文件',
  folder: '文件夹',
  directory: '目录',
  dir: '目录',
  path: '路径',
  disk: '磁盘',
  drive: '盘符',
  search: '搜索',
  find: '查找',
  filter: '过滤',
  sort: '排序',
  hash: '哈希',
  encode: '编码',
  decode: '解码',
  encrypt: '加密',
  decrypt: '解密',
  compress: '压缩',
  archive: '归档',
  auth: '认证',
  login: '登录',
  token: '令牌',
  user: '用户',
  account: '账户',
  permission: '权限',
  role: '角色',
  request: '请求',
  response: '响应',
  query: '查询',
  db: '数据库',
  database: '数据库',
  migration: '迁移',
  schema: '结构',
  type: '类型',
  types: '类型',
  interface: '接口',
  class: '类',
  model: '模型',
  api: 'API',
  http: 'HTTP',
  url: 'URL',
  uri: 'URI',
  git: 'git',
  diff: '差异',
  merge: '合并',
  patch: '补丁',
  revert: '回退',
  dependency: '依赖',
  dependencies: '依赖',
  dep: '依赖',
  deps: '依赖',
  relation: '关系',
  report: '报告',
  comment: '注释',
  doc: '文档',
  docs: '文档',
  guide: '指南',
  example: '示例',
  demo: '演示',
  sample: '样例',
  template: '模板',
  snapshot: '快照',
  // ── 行为/状态 ──
  error: '错误',
  exception: '异常',
  debug: '调试',
  trace: '跟踪',
  profile: '剖析',
  metric: '指标',
  metrics: '指标',
  stats: '统计',
  count: '计数',
  size: '大小',
  limit: '限制',
  budget: '预算',
  gate: '闸门',
  guard: '守卫',
  task: '任务',
  job: '作业',
  worker: '后台任务',
  batch: '批处理',
  timer: '定时器',
  schedule: '调度',
  event: '事件',
  signal: '信号',
  hook: '钩子',
  hooks: '钩子',
  router: '路由',
  route: '路由',
  routes: '路由',
  middleware: '中间件',
  client: '客户端',
  server: '服务器',
  boot: '启动',
  init: '初始化',
  initialize: '初始化',
  setup: '安装',
  test: '测试',
  tests: '测试',
  spec: '规范',
  mock: '模拟',
  fixture: '测试数据',
  export: '导出',
  import: '导入',
  download: '下载',
  upload: '上传',
  sync: '同步',
  refresh: '刷新',
  reload: '重载',
  jump: '跳转',
  navigate: '导航',
  // ── 缩写词:原样保留,在合成词里当身份 ──
  ai: 'AI',
  ui: '界面',
  cli: '命令行',
  id: 'ID',
  fs: '文件系统'
}

/** 这些词翻译出来等于没说(全部由它们组成时,宁可不写字) */
const GENERIC_WORDS = new Set(['应用', '主', '文件', '数据', '基础'])

/** 把驼峰/下划线/连字符名字拆成小写单词:GitFileStatus → [git, file, status] */
export function splitNameTokens(name: string): string[] {
  return name
    .replace(/\.[^.]+$/, '') // 去后缀
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2') // camel 边界
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2') // 缩写词边界(HTTPServer → HTTP Server)
    .split(/[^A-Za-z0-9]+/)
    .map((t) => t.toLowerCase())
    .filter((t) => t.length >= 2 && !/^\d+$/.test(t))
}

/**
 * 名字 → 中文短标(纯函数,自测覆盖)。
 * 查表拼词;"应用/文件"这类空话词在有好词时退场;查不出任何词、或拼出来全是空话、
 * 或超过一句话的长度,都返回 null 让调用方退回原兜底链 —— 宁缺不硬翻。
 */
export function translateName(name: string): string | null {
  const tokens = splitNameTokens(name)
  const parts: string[] = []
  for (const token of tokens) {
    const hit = WORD_BOOK[token] ?? (token.endsWith('s') ? WORD_BOOK[token.slice(0, -1)] : undefined)
    if (hit !== undefined) parts.push(hit)
  }
  if (parts.length === 0 || parts.every((p) => GENERIC_WORDS.has(p))) return null
  const text = parts.join('')
  if (text.length > 14) return null
  return text
}
