// M0 默认模板(§9、§19):数值沿用 2026-10-02 手工实测的规格包(§23.1),
// 以便功能导出的包与实测对照答案逐项比对。
// 三层变量(§6.1):基础变量写死数值;组件变量与页面变量默认引用基础变量。
import type { TokenDef, TokenMap, TokenTier, TokenValue, UiFrameDoc } from './types.ts'
import { defaultDeviceId } from './devices.ts'
import { DEFAULT_ROOT_PX } from './units.ts'

type Entry = [group: string, name: string, label: string, value: TokenValue]

const px = (v: number): TokenValue => ({ kind: 'dimension', px: v })
const ref = (r: string): TokenValue => ({ kind: 'ref', ref: r })
const num = (v: number): TokenValue => ({ kind: 'number', value: v })
const weight = (v: number): TokenValue => ({ kind: 'fontWeight', value: v })
const color = (light: string, dark: string): TokenValue => ({ kind: 'color', light, dark })

const BASE: Entry[] = [
  ['color', 'bg', '页面背景', color('#FAFAF9', '#0C0A09')],
  ['color', 'surface', '表面', color('#FFFFFF', '#1C1917')],
  ['color', 'text', '主文字', color('#1C1917', '#FAFAF9')],
  ['color', 'text-secondary', '次要文字', color('#57534E', '#A8A29E')],
  ['color', 'border', '边框', color('#E7E5E4', '#292524')],
  ['color', 'border-strong', '强边框', color('#D6D3D1', '#44403C')],
  ['color', 'primary', '主色', color('#2563EB', '#60A5FA')],
  ['color', 'primary-hover', '主色 · 悬停', color('#1D4ED8', '#93C5FD')],
  ['color', 'primary-active', '主色 · 按下', color('#1E40AF', '#BFDBFE')],
  ['color', 'on-primary', '主色上的文字', color('#FFFFFF', '#0C0A09')],
  ['color', 'primary-subtle', '主色浅底', color('#EFF6FF', '#172554')],
  ['color', 'hover-bg', '悬停底', color('#F5F5F4', '#292524')],
  ['color', 'pressed-bg', '按下底', color('#E7E5E4', '#44403C')],
  ['color', 'focus', '焦点环', color('#2563EB', '#60A5FA')],
  [
    'font',
    'family',
    '界面字体',
    { kind: 'fontFamily', families: ['Inter Variable', 'Noto Sans SC Variable', 'sans-serif'] }
  ],
  ['font-size', 'sm', '字号 · 小', px(13)],
  ['font-size', 'md', '字号 · 中', px(14)],
  ['font-size', 'lg', '字号 · 大', px(16)],
  ['font-size', 'xl', '字号 · 特大', px(18)],
  ['font-size', '5xl', '字号 · 标题', px(48)],
  ['font-weight', 'regular', '字重 · 常规', weight(400)],
  ['font-weight', 'medium', '字重 · 中', weight(500)],
  ['font-weight', 'semibold', '字重 · 半粗', weight(600)],
  ['font-weight', 'bold', '字重 · 粗', weight(700)],
  ['line-height', 'tight', '行高 · 紧', num(1.25)],
  ['line-height', 'normal', '行高 · 常规', num(1.5)],
  ['line-height', 'relaxed', '行高 · 宽松', num(1.75)],
  ['space', '1', '间距 1', px(4)],
  ['space', '2', '间距 2', px(8)],
  ['space', '3', '间距 3', px(12)],
  ['space', '4', '间距 4', px(16)],
  ['space', '6', '间距 6', px(24)],
  ['space', '8', '间距 8', px(32)],
  ['space', '10', '间距 10', px(40)],
  ['space', '16', '间距 16', px(64)],
  ['space', '24', '间距 24', px(96)],
  ['radius', 'none', '圆角 · 无', px(0)],
  ['radius', 'sm', '圆角 · 小', px(4)],
  ['radius', 'md', '圆角 · 中', px(8)],
  ['radius', 'lg', '圆角 · 大', px(12)],
  ['radius', 'full', '圆角 · 全圆', px(999)],
  ['control', 'sm', '控件高 · 小', px(32)],
  ['control', 'md', '控件高 · 中', px(40)],
  ['control', 'lg', '控件高 · 大', px(48)],
  ['icon', 'sm', '图标 · 小', px(16)],
  ['icon', 'md', '图标 · 中', px(20)],
  ['icon', 'lg', '图标 · 大', px(24)],
  ['icon', 'stroke', '图标线宽', num(2)],
  ['border-width', '1', '描边宽度', px(1)],
  ['focus-ring', 'width', '焦点环宽度', px(2)],
  ['focus-ring', 'offset', '焦点环外距', px(2)],
  ['opacity', 'disabled', '禁用透明度', num(0.4)],
  [
    'shadow',
    'sm',
    '阴影 · 小',
    {
      kind: 'shadow',
      x: 0,
      y: 1,
      blur: 2,
      spread: 0,
      light: 'rgba(28, 25, 23, 0.06)',
      dark: 'rgba(0, 0, 0, 0.4)'
    }
  ],
  [
    'shadow',
    'md',
    '阴影 · 中',
    {
      kind: 'shadow',
      x: 0,
      y: 4,
      blur: 12,
      spread: 0,
      light: 'rgba(28, 25, 23, 0.08)',
      dark: 'rgba(0, 0, 0, 0.5)'
    }
  ],
  // 响应式断点(§7.2):典型页 CSS 的 @media 边界从这里取数
  ['bp', 'sm', '断点 · 小屏', px(640)],
  ['bp', 'md', '断点 · 中屏', px(768)],
  ['bp', 'lg', '断点 · 大屏', px(1024)],
  ['bp', 'xl', '断点 · 特大屏', px(1280)]
]

const COMPONENT: Entry[] = [
  ['btn', 'height-sm', '高度 · 小', ref('control-sm')],
  ['btn', 'height-md', '高度 · 中', ref('control-md')],
  ['btn', 'height-lg', '高度 · 大', ref('control-lg')],
  ['btn', 'padding-x-sm', '左右内边距 · 小', ref('space-3')],
  ['btn', 'padding-x-md', '左右内边距 · 中', ref('space-4')],
  ['btn', 'padding-x-lg', '左右内边距 · 大', ref('space-6')],
  ['btn', 'font-size-sm', '字号 · 小', ref('font-size-sm')],
  ['btn', 'font-size-md', '字号 · 中', ref('font-size-md')],
  ['btn', 'font-size-lg', '字号 · 大', ref('font-size-lg')],
  ['btn', 'font-weight', '字重', ref('font-weight-medium')],
  ['btn', 'line-height', '行高', ref('line-height-tight')],
  ['btn', 'radius', '圆角', ref('radius-md')],
  ['btn', 'gap', '图标与文字间距', ref('space-2')],
  ['btn', 'icon-size', '图标尺寸', ref('icon-md')],
  ['btn', 'border-width', '描边宽度', ref('border-width-1')],
  ['card', 'padding', '内边距', ref('space-6')],
  ['card', 'radius', '圆角', ref('radius-lg')],
  ['card', 'border-width', '描边宽度', ref('border-width-1')],
  ['card', 'shadow', '阴影', ref('shadow-sm')],
  ['card', 'icon-box', '图标底块尺寸', ref('space-10')],
  ['card', 'icon-radius', '图标底块圆角', ref('radius-md')],
  ['card', 'icon-size', '图标尺寸', ref('icon-md')],
  ['card', 'icon-gap', '图标底块下间距', ref('space-4')],
  ['card', 'title-size', '标题字号', ref('font-size-xl')],
  ['card', 'title-weight', '标题字重', ref('font-weight-semibold')],
  ['card', 'title-line-height', '标题行高', ref('line-height-tight')],
  ['card', 'title-gap', '标题下间距', ref('space-2')],
  ['card', 'text-size', '说明字号', ref('font-size-md')],
  ['card', 'text-line-height', '说明行高', ref('line-height-normal')],
  ['ibtn', 'size-sm', '按钮尺寸 · 小', ref('control-sm')],
  ['ibtn', 'size-md', '按钮尺寸 · 中', ref('control-md')],
  ['ibtn', 'size-lg', '按钮尺寸 · 大', ref('control-lg')],
  ['ibtn', 'icon-size', '图标尺寸', ref('icon-md')],
  ['ibtn', 'radius', '圆角', ref('radius-md')],
  ['ibtn', 'border-width', '描边宽度', ref('border-width-1')],
  ['sw', 'width-md', '轨道宽 · 中', px(44)],
  ['sw', 'height-md', '轨道高 · 中', ref('space-6')],
  ['sw', 'thumb-md', '滑块 · 中', px(18)],
  ['sw', 'inset-md', '滑块内缩 · 中', px(3)],
  ['sw', 'travel-md', '滑块行程 · 中', px(20)],
  ['sw', 'width-sm', '轨道宽 · 小', px(36)],
  ['sw', 'height-sm', '轨道高 · 小', px(20)],
  ['sw', 'thumb-sm', '滑块 · 小', px(14)],
  ['sw', 'inset-sm', '滑块内缩 · 小', px(3)],
  ['sw', 'travel-sm', '滑块行程 · 小', px(16)],
  ['sw', 'thumb-pop', '滑块 · 外凸', px(26)],
  ['sw', 'travel-pop', '滑块行程 · 外凸', px(19)],
  ['sw', 'travel-pop-sm', '滑块行程 · 外凸小', px(13)],
  ['sw', 'radius', '轨道圆角', ref('radius-full')],
  ['sw', 'border-width', '描边宽度', ref('border-width-1')],
  ['sw', 'off-bg', '关态底色', color('#E7E5E4', '#3F3F46')],
  ['sw', 'off-border', '关态描边', color('#D6D3D1', '#52525B')],
  ['sw', 'thumb-bg', '滑块颜色', color('#FFFFFF', '#FFFFFF')],
  ['sw', 'thumb-shadow', '滑块阴影', ref('shadow-sm')],
  ['chk', 'size-md', '尺寸 · 中', ref('icon-md')],
  ['chk', 'size-sm', '尺寸 · 小', ref('icon-sm')],
  ['chk', 'radius', '圆角', ref('radius-sm')],
  ['chk', 'border-width', '描边宽度', ref('border-width-1')],
  ['chk', 'mark-md', '勾号尺寸 · 中', px(14)],
  ['chk', 'mark-sm', '勾号尺寸 · 小', px(12)],
  ['chk', 'mark-stroke', '勾号线宽', num(3)],
  ['ipt', 'width', '宽度', px(240)],
  ['ipt', 'height-sm', '高度 · 小', ref('control-sm')],
  ['ipt', 'height-md', '高度 · 中', ref('control-md')],
  ['ipt', 'height-lg', '高度 · 大', ref('control-lg')],
  ['ipt', 'font-size-sm', '字号 · 小', ref('font-size-sm')],
  ['ipt', 'font-size-md', '字号 · 中', ref('font-size-md')],
  ['ipt', 'font-size-lg', '字号 · 大', ref('font-size-lg')],
  ['ipt', 'padding-x', '左右内边距', ref('space-3')],
  ['ipt', 'gap', '图标与文字间距', ref('space-2')],
  ['ipt', 'icon-size', '图标尺寸', px(18)],
  ['ipt', 'radius', '圆角', ref('radius-md')],
  ['ipt', 'border-width', '描边宽度', ref('border-width-1')],
  ['tab', 'font-size-sm', '字号 · 小', ref('font-size-sm')],
  ['tab', 'font-size-md', '字号 · 中', ref('font-size-md')],
  ['tab', 'padding-y-sm', '上下内边距 · 小', ref('space-1')],
  ['tab', 'padding-y-md', '上下内边距 · 中', ref('space-2')],
  ['tab', 'padding-x-sm', '左右内边距 · 小', ref('space-3')],
  ['tab', 'padding-x-md', '左右内边距 · 中', ref('space-4')],
  ['tab', 'font-weight', '字重', ref('font-weight-medium')],
  ['tab', 'line-w', '下划线宽', px(2)],
  ['tab', 'gap', '页签间距', ref('space-1')],
  ['tab', 'seg-pad', '分段容器内边距', ref('space-1')],
  ['tab', 'seg-radius', '分段页签圆角', ref('radius-md')],
  ['tab', 'seg-outer-radius', '分段容器圆角', ref('radius-lg')],
  ['tab', 'seg-shadow', '分段选中阴影', ref('shadow-sm')],
  ['li', 'width', '行宽', px(360)],
  ['li', 'gap', '内容间距', ref('space-3')],
  ['li', 'padding-y', '上下内边距', ref('space-3')],
  ['li', 'padding-x', '左右内边距', ref('space-4')],
  ['li', 'divider-w', '分割线宽', ref('border-width-1')],
  ['li', 'icon-box', '前置图标位尺寸', ref('icon-lg')],
  ['li', 'icon-size', '前置图标尺寸', ref('icon-md')],
  ['li', 'avatar', '头像尺寸', px(36)],
  ['li', 'avatar-bg', '头像底色', ref('color-primary-subtle')],
  ['li', 'avatar-fg', '头像文字色', ref('color-primary')],
  ['li', 'avatar-fs', '头像字号', ref('font-size-md')],
  ['li', 'avatar-fw', '头像字重', ref('font-weight-medium')],
  ['li', 'sub-gap', '主副行间距', ref('space-1')],
  ['li', 'title-size', '标题字号', ref('font-size-md')],
  ['li', 'title-weight', '标题字重', ref('font-weight-medium')],
  ['li', 'title-line-height', '标题行高', ref('line-height-tight')],
  ['li', 'sub-size', '副行字号', ref('font-size-sm')],
  ['li', 'sub-line-height', '副行行高', ref('line-height-normal')],
  ['li', 'trail-icon', '尾部图标尺寸', ref('icon-sm')],
  ['li', 'value-size', '尾部数值字号', ref('font-size-sm')],
  ['tip', 'font-size', '字号', ref('font-size-sm')],
  ['tip', 'padding-y', '上下内边距', ref('space-1')],
  ['tip', 'padding-x', '左右内边距', ref('space-2')],
  ['tip', 'radius', '圆角', ref('radius-md')],
  ['tip', 'shadow', '阴影', ref('shadow-md')],
  ['tip', 'arrow-size', '箭头尺寸', px(8)],
  ['tip', 'arrow-drop', '箭头下探', px(-4)],
  ['tip', 'border-width', '描边宽度', ref('border-width-1')],
  ['tip', 'dark-bg', '深色底', ref('color-text')],
  ['tip', 'dark-fg', '深色底文字', ref('color-surface')],
  ['tip', 'light-bg', '浅色底', ref('color-surface')],
  ['tip', 'light-fg', '浅色底文字', ref('color-text')],
  // ── M3-b 扩编组件 ─────────────────────────────────────────
  ['rdo', 'size-md', '单选尺寸 · 中', ref('icon-md')],
  ['rdo', 'size-sm', '单选尺寸 · 小', ref('icon-sm')],
  ['rdo', 'dot-md', '内点尺寸 · 中', px(10)],
  ['rdo', 'dot-sm', '内点尺寸 · 小', px(8)],
  ['rdo', 'border-width', '描边宽度', ref('border-width-1')],
  ['rdo', 'off-border', '未选描边', ref('color-border-strong')],
  ['seg', 'pad', '容器内边距', ref('space-1')],
  ['seg', 'gap', '段间距', ref('space-1')],
  ['seg', 'outer-radius', '容器圆角', ref('radius-lg')],
  ['seg', 'it-radius', '段圆角', ref('radius-md')],
  ['seg', 'it-padding-y', '段上下内边距', ref('space-1')],
  ['seg', 'it-padding-x', '段左右内边距', ref('space-3')],
  ['seg', 'font-size', '段字号', ref('font-size-md')],
  ['seg', 'bg', '容器底色', ref('color-hover-bg')],
  ['seg', 'shadow', '选中段阴影', ref('shadow-sm')],
  ['sld', 'width', '轨道长', px(240)],
  ['sld', 'track-h', '轨道高', ref('space-1')],
  ['sld', 'track-bg', '轨道底色', ref('color-border')],
  ['sld', 'thumb', '滑块尺寸', ref('icon-sm')],
  ['sld', 'thumb-bg', '滑块颜色', ref('color-primary')],
  ['sld', 'thumb-shadow', '滑块阴影', ref('shadow-sm')],
  ['sld', 'hover-ring', '悬停光圈宽度', px(8)],
  ['sld', 'hover-bg', '悬停光圈颜色', ref('color-primary-subtle')],
  ['sld', 'active-ring', '按下光圈宽度', px(10)],
  // 滑块上提量 = (轨道高 - 滑块尺寸) / 2;改轨道/滑块尺寸时同步调
  ['sld', 'thumb-raise', '滑块上提量', px(-6)],
  ['sel', 'width', '宽度', px(200)],
  ['sel', 'height-md', '高度 · 中', ref('control-md')],
  ['sel', 'padding-x', '左右内边距', ref('space-3')],
  ['sel', 'font-size', '字号', ref('font-size-md')],
  ['sel', 'icon-size', '箭头尺寸', ref('icon-md')],
  ['sel', 'radius', '圆角', ref('radius-md')],
  ['sel', 'border-width', '描边宽度', ref('border-width-1')],
  ['stp', 'height', '高度', ref('control-sm')],
  ['stp', 'btn-width', '按钮宽', ref('control-sm')],
  ['stp', 'val-width', '数值区最小宽', px(40)],
  ['stp', 'val-padding-x', '数值区左右内边距', ref('space-1')],
  ['stp', 'font-size', '字号', ref('font-size-md')],
  ['stp', 'radius', '圆角', ref('radius-md')],
  ['stp', 'border-width', '描边宽度', ref('border-width-1')],
  ['rate', 'size', '星星尺寸', ref('icon-lg')],
  ['rate', 'gap', '星星间距', ref('space-1')],
  ['rate', 'on', '选中色', ref('color-primary')],
  ['rate', 'off', '未选色', ref('color-border-strong')],
  ['ta', 'width', '宽度', px(280)],
  ['ta', 'min-height', '最小高度', px(80)],
  ['ta', 'padding-y', '上下内边距', ref('space-2')],
  ['ta', 'padding-x', '左右内边距', ref('space-3')],
  ['ta', 'font-size', '字号', ref('font-size-md')],
  ['ta', 'radius', '圆角', ref('radius-md')],
  ['ta', 'border-width', '描边宽度', ref('border-width-1')],
  ['srch', 'width', '宽度', px(240)],
  ['srch', 'height', '高度', ref('control-md')],
  ['srch', 'padding-x', '左右内边距', ref('space-4')],
  ['srch', 'gap', '图标与文字间距', ref('space-2')],
  ['srch', 'icon-size', '图标尺寸', ref('icon-md')],
  ['srch', 'font-size', '字号', ref('font-size-md')],
  ['srch', 'radius', '圆角', ref('radius-full')],
  ['srch', 'border-width', '描边宽度', ref('border-width-1')],
  ['bgrp', 'height', '高度', ref('control-md')],
  ['bgrp', 'padding-x', '按钮左右内边距', ref('space-3')],
  ['bgrp', 'font-size', '字号', ref('font-size-md')],
  ['bgrp', 'radius', '圆角', ref('radius-md')],
  ['bgrp', 'border-width', '描边宽度', ref('border-width-1')],
  ['lnk', 'font-size', '字号', ref('font-size-md')],
  ['lnk', 'color', '颜色', ref('color-primary')],
  ['lnk', 'hover', '悬停色', ref('color-primary-hover')],
  ['lnk', 'gap', '图标与文字间距', ref('space-2')],
  ['lnk', 'icon-size', '图标尺寸', ref('icon-md')],
  // ── M3-b 第二批:反馈与数据展示 ────────────────────────────
  ['toast', 'padding-y', '上下内边距', ref('space-3')],
  ['toast', 'padding-x', '左右内边距', ref('space-4')],
  ['toast', 'gap', '内容与动作间距', ref('space-4')],
  ['toast', 'radius', '圆角', ref('radius-md')],
  ['toast', 'font-size', '字号', ref('font-size-md')],
  ['toast', 'bg', '底色', ref('color-text')],
  ['toast', 'fg', '文字色', ref('color-surface')],
  ['toast', 'shadow', '阴影', ref('shadow-md')],
  ['bnr', 'width', '宽度', px(420)],
  ['bnr', 'padding-y', '上下内边距', ref('space-3')],
  ['bnr', 'padding-x', '左右内边距', ref('space-4')],
  ['bnr', 'radius', '圆角', ref('radius-md')],
  ['bnr', 'border-width', '描边宽度', ref('border-width-1')],
  ['bnr', 'font-size', '字号', ref('font-size-md')],
  ['prog', 'width', '轨道长', px(240)],
  ['prog', 'height', '轨道高', ref('space-1')],
  ['prog', 'track-bg', '轨道底色', ref('color-border')],
  ['prog', 'fill', '填充长度', px(144)],
  ['spin', 'size', '尺寸', ref('icon-lg')],
  ['spin', 'size-sm', '尺寸 · 小', ref('icon-sm')],
  ['spin', 'width', '线宽', px(3)],
  ['spin', 'width-sm', '线宽 · 小', ref('border-width-1')],
  ['spin', 'track', '轨道色', ref('color-border')],
  ['skl', 'bg', '占位底色', ref('color-hover-bg')],
  ['skl', 'radius', '圆角', ref('radius-md')],
  ['skl', 'line-h', '行占位高', ref('font-size-md')],
  ['skl', 'line-w', '行占位宽', px(240)],
  ['skl', 'line-w60', '行占位宽 · 中', px(144)],
  ['skl', 'line-w40', '行占位宽 · 短', px(96)],
  ['skl', 'circle', '圆占位尺寸', ref('control-md')],
  ['emp', 'width', '宽度', px(320)],
  ['emp', 'padding-y', '上下内边距', ref('space-8')],
  ['emp', 'padding-x', '左右内边距', ref('space-6')],
  ['emp', 'gap', '区块间距', ref('space-3')],
  ['emp', 'icon-box', '图标底块', ref('space-16')],
  ['emp', 'icon', '图标尺寸', ref('icon-lg')],
  ['emp', 'title-size', '标题字号', ref('font-size-lg')],
  ['emp', 'text-size', '说明字号', ref('font-size-md')],
  ['bdg', 'min', '最小宽', ref('icon-md')],
  ['bdg', 'height', '高度', ref('icon-md')],
  ['bdg', 'padding-x', '左右内边距', ref('space-1')],
  ['bdg', 'font-size', '字号', ref('font-size-sm')],
  ['bdg', 'dot', '红点儿尺寸', ref('space-2')],
  ['tag', 'height', '高度', ref('control-sm')],
  ['tag', 'padding-x', '左右内边距', ref('space-3')],
  ['tag', 'gap', '内容与×间距', ref('space-1')],
  ['tag', 'radius', '圆角', ref('radius-full')],
  ['tag', 'border-width', '描边宽度', ref('border-width-1')],
  ['tag', 'font-size', '字号', ref('font-size-sm')],
  ['tag', 'x-size', '关闭钮尺寸', ref('icon-sm')],
  ['tag', 'x-font', '关闭钮字号', ref('font-size-md')],
  ['avt', 'size-md', '尺寸 · 中', ref('control-md')],
  ['avt', 'size-sm', '尺寸 · 小', ref('control-sm')],
  ['avt', 'size-lg', '尺寸 · 大', px(56)],
  ['avt', 'radius', '圆角', ref('radius-full')],
  ['avt', 'bg', '底色', ref('color-primary-subtle')],
  ['avt', 'fg', '文字色', ref('color-primary')],
  ['avt', 'font-size-md', '字号 · 中', ref('font-size-md')],
  ['avt', 'font-size-sm', '字号 · 小', ref('font-size-sm')],
  ['avt', 'font-size-lg', '字号 · 大', ref('font-size-lg')],
  ['avt', 'font-weight', '字重', ref('font-weight-medium')],
  ['avt', 'icon-size', '图标尺寸', ref('icon-md')],
  ['div', 'width', '线宽', ref('border-width-1')],
  ['div', 'length', '水平线长', px(240)],
  ['div', 'v-length', '竖线高', ref('icon-md')],
  ['div', 'margin-y', '水平上下间距', ref('space-2')],
  ['div', 'margin-x', '竖线左右间距', ref('space-2')],
  // ── M3-b 第三批:导航 ──────────────────────────────────────
  ['abar', 'width', '宽度', px(480)],
  ['abar', 'height', '高度', ref('control-lg')],
  ['abar', 'padding-x', '左右内边距', ref('space-4')],
  ['abar', 'gap', '区块间距', ref('space-4')],
  ['abar', 'nav-gap', '导航项间距', ref('space-6')],
  ['abar', 'title-size', '标题字号', ref('font-size-lg')],
  ['abar', 'font-size', '导航字号', ref('font-size-md')],
  ['abar', 'border-width', '底边线宽', ref('border-width-1')],
  ['sbar', 'width', '宽度', px(200)],
  ['sbar', 'height', '高度', px(240)],
  ['sbar', 'padding-y', '上下内边距', ref('space-3')],
  ['sbar', 'padding-x', '左右内边距', ref('space-2')],
  ['sbar', 'gap', '条目间距', ref('space-1')],
  ['sbar', 'item-height', '条目高度', ref('control-sm')],
  ['sbar', 'item-padding-x', '条目左右内边距', ref('space-3')],
  ['sbar', 'item-radius', '条目圆角', ref('radius-md')],
  ['sbar', 'item-gap', '图标与文字间距', ref('space-3')],
  ['sbar', 'font-size', '字号', ref('font-size-md')],
  ['sbar', 'icon-size', '图标尺寸', ref('icon-md')],
  ['sbar', 'border-width', '右描边宽', ref('border-width-1')],
  ['rail', 'width', '栏宽', px(56)],
  ['rail', 'height', '栏高', px(240)],
  ['rail', 'padding-y', '上下内边距', ref('space-2')],
  ['rail', 'gap', '条目间距', ref('space-1')],
  ['rail', 'item', '条目尺寸', ref('control-md')],
  ['rail', 'item-radius', '条目圆角', ref('radius-md')],
  ['rail', 'icon-size', '图标尺寸', ref('icon-md')],
  ['rail', 'border-width', '右描边宽', ref('border-width-1')],
  ['bbar', 'width', '宽度', px(360)],
  ['bbar', 'height', '高度', px(56)],
  ['bbar', 'item-gap', '图标与文字间距', ref('space-1')],
  ['bbar', 'font-size', '字号', ref('font-size-sm')],
  ['bbar', 'icon-size', '图标尺寸', ref('icon-lg')],
  ['bbar', 'border-width', '顶描边宽', ref('border-width-1')],
  ['crumb', 'gap', '项间距', ref('space-2')],
  ['crumb', 'font-size', '字号', ref('font-size-sm')],
  ['pgn', 'gap', '页码间距', ref('space-2')],
  ['pgn', 'item', '页码尺寸', ref('control-sm')],
  ['pgn', 'padding-x', '页码左右内边距', ref('space-2')],
  ['pgn', 'radius', '圆角', ref('radius-md')],
  ['pgn', 'border-width', '描边宽度', ref('border-width-1')],
  ['pgn', 'font-size', '字号', ref('font-size-md')],
  ['stps', 'gap', '步骤间距', ref('space-2')],
  ['stps', 'item-gap', '圆点与文字间距', ref('space-2')],
  ['stps', 'dot', '圆点尺寸', ref('icon-lg')],
  ['stps', 'dot-font', '圆点字号', ref('font-size-sm')],
  ['stps', 'font-size', '步骤字号', ref('font-size-md')],
  ['stps', 'border-width', '圆点描边宽', ref('border-width-1')],
  ['stps', 'link-w', '连线长', ref('space-8')],
  ['fab', 'size', '尺寸', px(56)],
  ['fab', 'size-sm', '尺寸 · 小', ref('control-md')],
  ['fab', 'radius', '圆角', ref('radius-full')],
  ['fab', 'icon-size', '图标尺寸', ref('icon-lg')],
  ['fab', 'shadow', '阴影', ref('shadow-md')],
  // ── M3-b 第三批:浮层 ──────────────────────────────────────
  ['menu', 'min-width', '最小宽', px(160)],
  ['menu', 'pad', '容器内边距', ref('space-1')],
  ['menu', 'item-height', '条目高度', ref('control-sm')],
  ['menu', 'item-padding-x', '条目左右内边距', ref('space-3')],
  ['menu', 'item-radius', '条目圆角', ref('radius-sm')],
  ['menu', 'font-size', '字号', ref('font-size-md')],
  ['menu', 'radius', '圆角', ref('radius-md')],
  ['menu', 'border-width', '描边宽度', ref('border-width-1')],
  ['menu', 'shadow', '阴影', ref('shadow-md')],
  ['menu', 'danger', '危险项色', color('#DC2626', '#F87171')],
  ['pop', 'width', '宽度', px(240)],
  ['pop', 'padding', '内边距', ref('space-4')],
  ['pop', 'radius', '圆角', ref('radius-md')],
  ['pop', 'border-width', '描边宽度', ref('border-width-1')],
  ['pop', 'shadow', '阴影', ref('shadow-md')],
  ['pop', 'title-size', '标题字号', ref('font-size-md')],
  ['pop', 'title-gap', '标题下间距', ref('space-1')],
  ['pop', 'text-size', '正文字号', ref('font-size-sm')],
  ['dlg', 'mask-w', '遮罩宽(演示)', px(480)],
  ['dlg', 'mask-h', '遮罩高(演示)', px(280)],
  ['dlg', 'mask-bg', '遮罩色', color('rgba(28, 25, 23, 0.4)', 'rgba(0, 0, 0, 0.6)')],
  ['dlg', 'width', '对话框宽', px(360)],
  ['dlg', 'padding', '内边距', ref('space-6')],
  ['dlg', 'gap', '区块间距', ref('space-3')],
  ['dlg', 'radius', '圆角', ref('radius-lg')],
  ['dlg', 'shadow', '阴影', ref('shadow-md')],
  ['dlg', 'title-size', '标题字号', ref('font-size-lg')],
  ['dlg', 'text-size', '正文字号', ref('font-size-md')],
  ['dlg', 'actions-gap', '按钮间距', ref('space-3')],
  ['dlg', 'actions-margin', '按钮上间距', ref('space-4')],
  ['dwr', 'stage-w', '演示舞台宽', px(480)],
  ['dwr', 'stage-h', '演示舞台高', px(240)],
  ['dwr', 'width', '抽屉宽', px(280)],
  ['dwr', 'padding', '内边距', ref('space-6')],
  ['dwr', 'gap', '区块间距', ref('space-3')],
  ['dwr', 'border-width', '边线宽', ref('border-width-1')],
  ['dwr', 'shadow', '阴影', ref('shadow-md')],
  ['dwr', 'title-size', '标题字号', ref('font-size-lg')],
  ['dwr', 'text-size', '正文字号', ref('font-size-md')],
  ['sht', 'stage-w', '演示舞台宽', px(360)],
  ['sht', 'stage-h', '演示舞台高', px(300)],
  ['sht', 'mask-bg', '遮罩色', color('rgba(28, 25, 23, 0.4)', 'rgba(0, 0, 0, 0.6)')],
  ['sht', 'padding-y', '上下内边距', ref('space-3')],
  ['sht', 'padding-x', '左右内边距', ref('space-4')],
  ['sht', 'gap', '区块间距', ref('space-2')],
  ['sht', 'radius', '顶部圆角', ref('radius-lg')],
  ['sht', 'shadow', '阴影', ref('shadow-md')],
  ['sht', 'grab-w', '把手宽', ref('space-10')],
  ['sht', 'grab-h', '把手高', ref('space-1')],
  ['ash', 'width', '宽度', px(360)],
  ['ash', 'pad', '容器内边距', ref('space-2')],
  ['ash', 'gap', '组间距', ref('space-2')],
  ['ash', 'radius', '组圆角', ref('radius-lg')],
  ['ash', 'item-height', '条目高度', ref('control-lg')],
  ['ash', 'font-size', '字号', ref('font-size-lg')],
  ['ash', 'border-width', '分隔线宽', ref('border-width-1')],
  ['ash', 'stage-bg', '演示底色', ref('color-bg')],
  ['ash', 'danger', '危险项色', color('#DC2626', '#F87171')],
  // ── M3-b 第四批:容器与平台 ────────────────────────────────
  ['acdn', 'width', '宽度', px(360)],
  ['acdn', 'radius', '圆角', ref('radius-lg')],
  ['acdn', 'border-width', '描边宽度', ref('border-width-1')],
  ['acdn', 'padding-x', '左右内边距', ref('space-4')],
  ['acdn', 'head-padding-y', '头部上下内边距', ref('space-3')],
  ['acdn', 'body-padding-y', '内容上下内边距', ref('space-3')],
  ['acdn', 'font-size', '头部字号', ref('font-size-md')],
  ['acdn', 'text-size', '内容字号', ref('font-size-md')],
  ['acdn', 'icon-size', '箭头尺寸', ref('icon-md')],
  ['tbl', 'width', '宽度', px(480)],
  ['tbl', 'radius', '圆角', ref('radius-md')],
  ['tbl', 'border-width', '描边宽度', ref('border-width-1')],
  ['tbl', 'padding-x', '单元格左右内边距', ref('space-4')],
  ['tbl', 'head-padding-y', '表头上下内边距', ref('space-2')],
  ['tbl', 'cell-padding-y', '单元格上下内边距', ref('space-3')],
  ['tbl', 'font-size', '字号', ref('font-size-md')],
  ['tbl', 'head-font-size', '表头字号', ref('font-size-sm')],
  ['tbl', 'head-bg', '表头底色', ref('color-hover-bg')],
  ['tree', 'width', '宽度', px(280)],
  ['tree', 'pad', '容器内边距', ref('space-2')],
  ['tree', 'gap', '条目间距', ref('space-1')],
  ['tree', 'radius', '圆角', ref('radius-md')],
  ['tree', 'border-width', '描边宽度', ref('border-width-1')],
  ['tree', 'font-size', '字号', ref('font-size-md')],
  ['tree', 'item-height', '条目高度', ref('control-sm')],
  ['tree', 'item-padding-x', '条目左右内边距', ref('space-2')],
  ['tree', 'item-radius', '条目圆角', ref('radius-md')],
  ['tree', 'item-gap', '图标与文字间距', ref('space-2')],
  ['tree', 'indent', '层级缩进', ref('space-6')],
  ['tree', 'icon-size', '箭头尺寸', ref('icon-sm')],
  ['tline', 'width', '宽度', px(320)],
  ['tline', 'dot', '圆点尺寸', px(12)],
  ['tline', 'dot-margin', '圆点上偏移', px(2)],
  ['tline', 'line-x', '竖线位置', px(6)],
  ['tline', 'border-width', '竖线宽', ref('border-width-1')],
  ['tline', 'item-gap', '圆点与内容间距', ref('space-3')],
  ['tline', 'item-gap-y', '条目间距', ref('space-6')],
  ['tline', 'title-size', '标题字号', ref('font-size-md')],
  ['tline', 'sub-size', '时间字号', ref('font-size-sm')],
  ['tbar', 'width', '宽度', px(480)],
  ['tbar', 'height', '高度', ref('control-sm')],
  ['tbar', 'padding-x', '左右内边距', ref('space-3')],
  ['tbar', 'gap', '控制钮间距', ref('space-2')],
  ['tbar', 'ctl-size', '控制钮尺寸', px(12)],
  ['tbar', 'font-size', '字号', ref('font-size-sm')],
  ['tbar', 'border-width', '底边线宽', ref('border-width-1')],
  ['tbar', 'close-bg', '关闭钮颜色', color('#FF5F57', '#FF5F57')],
  ['stat', 'width', '宽度', px(480)],
  ['stat', 'height', '高度', ref('space-6')],
  ['stat', 'padding-x', '左右内边距', ref('space-3')],
  ['stat', 'gap', '区块间距', ref('space-3')],
  ['stat', 'sep-h', '分隔线高', ref('space-3')],
  ['stat', 'font-size', '字号', ref('font-size-sm')],
  ['stat', 'border-width', '顶边线宽', ref('border-width-1')],
  ['spl', 'width', '条宽', ref('space-1')],
  ['spl', 'length', '条长', px(160)],
  ['pnav', 'width', '宽度', px(360)],
  ['pnav', 'height', '高度', ref('control-lg')],
  ['pnav', 'padding-x', '左右内边距', ref('space-4')],
  ['pnav', 'back-size', '返回钮尺寸', ref('control-sm')],
  ['pnav', 'icon-size', '返回图标尺寸', ref('icon-md')],
  ['pnav', 'title-size', '标题字号', ref('font-size-lg')],
  ['pnav', 'border-width', '底边线宽', ref('border-width-1')],
  ['swr', 'width', '行宽', px(360)],
  ['swr', 'height', '行高', px(56)],
  ['swr', 'padding-x', '内容左右内边距', ref('space-4')],
  ['swr', 'radius', '圆角', ref('radius-md')],
  ['swr', 'font-size', '字号', ref('font-size-md')],
  ['swr', 'act-width', '操作钮宽', px(80)],
  ['swr', 'danger-bg', '删除钮底色', color('#DC2626', '#DC2626')],
  ['ptr', 'width', '宽度', px(360)],
  ['ptr', 'padding-y', '上下内边距', ref('space-3')],
  ['ptr', 'gap', '图标与文字间距', ref('space-2')],
  ['ptr', 'icon-size', '图标位尺寸', ref('control-sm')],
  ['ptr', 'icon', '图标尺寸', ref('icon-md')],
  ['ptr', 'font-size', '字号', ref('font-size-sm')],
  ['ptr', 'border-width', '描边宽度', ref('border-width-1')],
  // 变体轴补全(M3-g,§7.4):浅底按钮悬停底与危险语义三态
  ['btn', 'tint-hover-bg', '浅底按钮 · 悬停底', color('#DBEAFE', '#1E3A8A')],
  ['btn', 'danger-bg', '危险按钮 · 底', color('#DC2626', '#B91C1C')],
  ['btn', 'danger-hover-bg', '危险按钮 · 悬停底', color('#B91C1C', '#991B1B')],
  ['btn', 'danger-active-bg', '危险按钮 · 按下底', color('#991B1B', '#7F1D1D')]
]

const PAGE: Entry[] = [
  ['page', 'header-height', '顶栏高度', px(64)],
  ['page', 'gutter', '页面左右留白', ref('space-8')],
  ['page', 'logo-size', 'logo 字号', ref('font-size-xl')],
  ['page', 'nav-gap', '导航项间距', ref('space-8')],
  ['page', 'actions-gap', '顶栏按钮间距', ref('space-3')],
  ['page', 'hero-pad-top', '首屏上留白', ref('space-24')],
  ['page', 'hero-pad-bottom', '首屏下留白', ref('space-16')],
  ['page', 'hero-title-max', '标题最大宽度', px(640)],
  ['page', 'hero-title-size', '标题字号', ref('font-size-5xl')],
  ['page', 'hero-title-tracking', '标题字间距', { kind: 'em', value: -0.02 }],
  ['page', 'hero-text-gap', '标题与段落间距', ref('space-6')],
  ['page', 'hero-text-max', '段落最大宽度', px(576)],
  ['page', 'hero-text-size', '段落字号', ref('font-size-xl')],
  ['page', 'hero-actions-gap', '段落与按钮间距', ref('space-10')],
  ['page', 'hero-actions-spacing', '首屏按钮间距', ref('space-4')],
  ['page', 'content-max', '内容区最大宽度', px(1120)],
  ['page', 'features-columns', '卡片列数', num(3)],
  ['page', 'features-gap', '卡片间距', ref('space-6')],
  ['page', 'features-pad-bottom', '卡片区下留白', ref('space-24')],
  ['page', 'footer-pad', '页脚内边距', ref('space-8')],
  ['page', 'footer-text-size', '页脚字号', ref('font-size-md')],
  // 手机端示例页(§5.4):安全区与导航/列表/按钮排布的页面级变量
  ['app', 'safe-top', '顶部安全区(状态栏)', px(56)],
  ['app', 'safe-bottom', '底部安全区(手势条)', px(40)],
  ['app', 'nav-height', '导航栏高度', px(52)],
  ['app', 'nav-gap', '导航项间距', ref('space-2')],
  ['app', 'gutter', '页面左右留白', ref('space-4')],
  ['app', 'title-size', '导航标题字号', ref('font-size-lg')],
  ['app', 'title-weight', '导航标题字重', ref('font-weight-semibold')],
  ['app', 'body-gap', '内容区块间距', ref('space-4')],
  ['app', 'body-pad-y', '内容区上下留白', ref('space-4')],
  ['app', 'list-radius', '列表卡片圆角', ref('radius-lg')],
  ['app', 'cta-gap', '底部按钮上间距', ref('space-4')],
  // 典型页布局(M3-f):内容宽度、区块间距、卡片留白
  ['pg', 'content-max', '页面内容最大宽度', ref('page-content-max')],
  ['pg', 'narrow-max', '窄页面最大宽度', px(720)],
  ['pg', 'pad-y', '页面上下留白', ref('space-8')],
  ['pg', 'section-gap', '页面区块间距', ref('space-8')],
  ['pg', 'toolbar-gap', '工具行间距', ref('space-3')],
  ['pg', 'field-gap', '表单字段间距', ref('space-4')],
  ['pg', 'actions-gap', '操作按钮间距', ref('space-3')],
  ['pg', 'card-pad', '卡片内边距', ref('space-6')],
  ['pg', 'title-size', '页面标题字号', px(28)]
]

function build(entries: Entry[], tier: TokenTier, into: TokenMap): void {
  for (const [group, name, label, value] of entries) {
    const def: TokenDef = { path: [group, name], label, tier, value }
    into[`${group}-${name}`] = def
  }
}

/** 默认变量表的全新副本(调用方可随意改写) */
export function defaultTokens(): TokenMap {
  const tokens: TokenMap = {}
  build(BASE, 'base', tokens)
  build(COMPONENT, 'component', tokens)
  build(PAGE, 'page', tokens)
  return tokens
}

export function defaultDoc(): UiFrameDoc {
  return {
    schemaVersion: 1,
    name: '落地页示例',
    platform: 'desktop',
    device: defaultDeviceId('desktop'),
    template: 'minimal-desk',
    rootFontPx: DEFAULT_ROOT_PX,
    tokens: defaultTokens(),
    icons: {
      'demo-button': 'arrow-right',
      'demo-ibtn': 'ellipsis',
      'demo-check': 'check',
      'demo-input': 'search',
      'demo-li': 'bell',
      'demo-arrow': 'chevron-right',
      'demo-card': 'timer',
      'hero-cta': 'arrow-right',
      'feature-1': 'timer',
      'feature-2': 'music',
      'feature-3': 'dumbbell',
      'app-back': 'chevron-left',
      'app-bell': 'bell',
      'app-search': 'search',
      'app-row-1': 'dumbbell',
      'app-row-2': 'zap',
      'app-row-3': 'flame',
      'app-arrow': 'chevron-right',
      'demo-search': 'search',
      'demo-down': 'chevron-down',
      'demo-x': 'x'
    },
    customIcons: {},
    placed: []
  }
}
